# Generated by Django 6.0.7 on 2026-08-03 11:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(help_text='e.g., Man United vs Chelsea', max_length=200)),
                ('league', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('bet_type', models.CharField(choices=[('1X2', 'Match Result (1X2)'), ('OVER_UNDER', 'Over/Under Goals'), ('BTTS', 'Both Teams to Score'), ('HANDICAP', 'Asian Handicap'), ('DRAW_NO_BET', 'Draw No Bet'), ('DOUBLE_CHANCE', 'Double Chance')], max_length=20)),
                ('selection', models.CharField(help_text='e.g., Home Win, Over 2.5', max_length=100)),
                ('odds', models.FloatField()),
                ('stake', models.FloatField(help_text='Amount bet in Naira')),
                ('implied_probability', models.FloatField(blank=True, null=True)),
                ('your_probability', models.FloatField(blank=True, help_text='Your estimated probability %', null=True)),
                ('value', models.FloatField(blank=True, null=True)),
                ('result', models.CharField(choices=[('W', 'Win'), ('L', 'Loss'), ('P', 'Pending'), ('V', 'Void')], default='P', max_length=1)),
                ('profit_loss', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, help_text='Why did you make this bet?')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MatchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match', models.CharField(max_length=200)),
                ('league', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('home_win_rate', models.FloatField(blank=True, null=True)),
                ('away_win_rate', models.FloatField(blank=True, null=True)),
                ('home_goals_avg', models.FloatField(blank=True, null=True)),
                ('away_goals_avg', models.FloatField(blank=True, null=True)),
                ('h2h_home_wins', models.IntegerField(default=0)),
                ('h2h_away_wins', models.IntegerField(default=0)),
                ('h2h_draws', models.IntegerField(default=0)),
                ('home_form', models.CharField(blank=True, help_text='e.g., WWLWD', max_length=10)),
                ('away_form', models.CharField(blank=True, max_length=10)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
